### ISSUE TITLE
Unable to create new project file

### ISSUE THREAD

**Issue by dowdian** [DNN-Connect/DNN-Translator#10]
After downloading and installing v1.4 on Win10, I attempted to create a new project by pointing the app to the root folder of a fresh install of DNN 9.10.  The application shuts down immediately leaving the following two messages in the Event Viewer:

```
Application: Translator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.Reflection.RuntimeAssembly.nLoadFile(System.String, System.Security.Policy.Evidence)
   at System.Reflection.Assembly.LoadFile(System.String)
   at DotNetNuke.Translator.Common.ProjectSettings..ctor(System.String)
   at DotNetNuke.Translator.ViewModel.MainWindowViewModel.OpenLocation(System.Object, System.ComponentModel.DoWorkEventArgs)
   at System.ComponentModel.BackgroundWorker.OnDoWork(System.ComponentModel.DoWorkEventArgs)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(System.Object)

Exception Info: System.Reflection.TargetInvocationException
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at DotNetNuke.Translator.ViewModel.MainWindowViewModel.OpenNewCompleted(System.Object, System.ComponentModel.RunWorkerCompletedEventArgs)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(System.ComponentModel.RunWorkerCompletedEventArgs)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DotNetNuke.Translator.Application.Main
```

```
Faulting application name: Translator.exe, version: 1.4.0.0, time stamp: 0x5ec2ff12
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1566, time stamp: 0x0833f2d4
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x59c0
Faulting application start time: 0x01d84364828d218d
Faulting application path: C:\Program Files\DNN Community\DNN Translator\Translator.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: b5735576-1590-4d3f-b4d3-f4abeabeb74e
Faulting package full name: 
Faulting package-relative application ID: 
```

Any help you can offer would be most appreciated.

**Comment by enfJoao** [comment]
I second this issue.
