### ISSUE TITLE
App crashes when selecting the DNN install folder

### ISSUE THREAD

**Issue by enfJoao** [DNN-Connect/DNN-Translator#13]
Logs:

Log Name:      Application
Source:        Application Error
Date:          29/01/2024 22:40:38
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          x
Computer:      x
Description:
Faulting application name: Translator.exe, version: 1.4.1.0, time stamp: 0x65b778b1
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2792, time stamp: 0x3091b6fb
Exception code: 0xe0434352
Fault offset: 0x000000000006567c
Faulting process id: 0x0x1B38
Faulting application start time: 0x0x1DA5304253C59DD
Faulting application path: E:\DNNTranslation\Translator.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 5fe44fe5-b676-46ac-a4a7-7ba090b909f4
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-29T22:40:38.4699611Z" />
    <EventRecordID>24854</EventRecordID>
    <Correlation />
    <Execution ProcessID="17688" ThreadID="11692" />
    <Channel>Application</Channel>
    <Computer>XZTech</Computer>
    <Security UserID="S-1-5-21-409737550-3847818484-627542900-1001" />
  </System>
  <EventData>
    <Data Name="AppName">Translator.exe</Data>
    <Data Name="AppVersion">1.4.1.0</Data>
    <Data Name="AppTimeStamp">65b778b1</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.2792</Data>
    <Data Name="ModuleTimeStamp">3091b6fb</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">000000000006567c</Data>
    <Data Name="ProcessId">0x1b38</Data>
    <Data Name="ProcessCreationTime">0x1da5304253c59dd</Data>
    <Data Name="AppPath">E:\DNNTranslation\Translator.exe</Data>
    <Data Name="ModulePath">C:\Windows\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">5fe44fe5-b676-46ac-a4a7-7ba090b909f4</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          29/01/2024 22:40:38
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      XZTech
Description:
Application: Translator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.Reflection.RuntimeAssembly.nLoadFile(System.String, System.Security.Policy.Evidence)
   at System.Reflection.Assembly.LoadFile(System.String)
   at DotNetNuke.Translator.Common.ProjectSettings..ctor(System.String)
   at DotNetNuke.Translator.ViewModel.MainWindowViewModel.OpenLocation(System.String)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DotNetNuke.Translator.Application.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-29T22:40:38.3509837Z" />
    <EventRecordID>24853</EventRecordID>
    <Correlation />
    <Execution ProcessID="6968" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>x</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Translator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.Reflection.RuntimeAssembly.nLoadFile(System.String, System.Security.Policy.Evidence)
   at System.Reflection.Assembly.LoadFile(System.String)
   at DotNetNuke.Translator.Common.ProjectSettings..ctor(System.String)
   at DotNetNuke.Translator.ViewModel.MainWindowViewModel.OpenLocation(System.String)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DotNetNuke.Translator.Application.Main()

</Data>
  </EventData>
</Event>

**Comment by donker** [comment]
Do you have .net Framework 4.8 installed? The application was compiled against DNF 4.8.

**Comment by enfJoao** [comment]
Yes.
I tried the installer to make sure.

![image](https://github.com/DNN-Connect/DNN-Translator/assets/26518879/f32b85d1-0925-41ea-b90c-522bb03b34fc)

**Comment by david-poindexter** [comment]
1. What version is your operating system?
2. Did you install the .NET Framework 4.8 Runtime from https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48?
3. Are you an `Administrator` on your computer?  
4. Do you have any odd security/policy constraints on your computer?
5. Are you using anti-virus?  If so, have you tried temporarily pausing/disabling it and trying to run the app to see if there is perhaps something with the anti-virus software blocking it?

**Comment by enfJoao** [comment]
1. Win11 build 22631
2. This link, specificaly: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-web-installer
3. Yes. And I tried the exe with admin privileges.
4. None that I'm aware of.
5. Yes. Windows defender (if you consider it an AV). But I tried turning all features off.

**Comment by enfJoao** [comment]
Also tried with Win Server 22 and it also crashes.

**Comment by david-poindexter** [comment]
I just downloaded v1.4.1 and installed.  It runs as expected for me.  @enfJoao are you selecting the root folder for the DNN instance when you open?

**Comment by enfJoao** [comment]
My bad, I guess. I was pointing the app to a fresh download of dnn9. It actually needs a running version or at least a post-install folder.

**Comment by david-poindexter** [comment]
Glad you figured it out! 🎉

**Comment by enfJoao** [comment]
Now I kust need a manual on how to use the app :(
If you find the time, could you show the features or a quick "how to"?
Perhaps one of the online recorded meetings?

**Comment by david-poindexter** [comment]
> Now I kust need a manual on how to use the app :( If you find the time, could you show the features or a quick "how to"? Perhaps one of the online recorded meetings?

@enfJoao I think there is documentation (Word doc) in this folder: 
https://github.com/DNN-Connect/DNN-Translator/tree/master/_Documentation
